config/routes.rb
Rails.application.routes.draw do


 scope module: :public do

    root to: 'homes#top'
    get "/homes/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show ,:create] do
     collection { post 'confirm'}
     collection { get 'thanks'}
    end
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection { delete 'destroy_all'}
    end
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resource :customers, only: [:show, :edit, :update] do
     get 'confirm' => "customers#confirm"
     patch 'withdrawal' => "customers#withdrawal"
    end

 end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
    }

# 管理者用
# URL /admin/sign_in ...
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
 namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :customers, only: [:index, :show, :edit, :update] do
     resources :orders, only: [:index ,:show, :update]
     resources :order_details, only: [:update]
    end
    resources :genres, only: [:index, :show, :create, :edit, :update]

 end

 # scope module: :public do
 #    root 'homes#top'

 #    get 'customers/mypage' => 'customers#show', as: 'mypage'
 #    。
 #    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
 #    patch 'customers/information' => 'customers#update', as: 'update_information'
 #    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
 #    put 'customers/information' => 'customers#update'
 #    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
 #    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
 #    post 'orders/confirm' => 'orders#confirm'
 #    get 'orders/confirm' => 'orders#error'
 #    get 'orders/thanks' => 'orders#thanks', as: 'thanks'

 #    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
 #    resources :items, only: [:index, :show] do
 #      resources :cart_items, only: [:create, :update, :destroy]
 #    end
 #    resources :cart_items, only: [:index]
 #    resources :orders, only: [:new, :index, :create, :show]

 #  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  validates :is_active, inclusion: {in: [true, false]}

  has_one_attached :image

  def get_profile_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/flow01.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
   image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @items = Item.page(params[:page])
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class = "container">
  <div class = "p-3 text-black">
    <span class = "bg-light pr-3 pl-3 h5">商品編集</span>
  </div>

  <div class="row">
    <div class="col-md-7">
    <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>

      <table>

        <tr>
          <th class="p-2">商品画像</th>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>

        <tr>
            <th class="p-2">商品名</th>
            <td><%= f.text_field :name, autofocus: true, :placeholder => "商品名" %></td>
        </tr>

        <tr>
            <th class="p-2">商品説明</th>
            <td><%= f.text_area :introduction, rows:3, autofocus: true, id:"inputIntroduction", :placeholder => "ここに説明文を記述します" %></td>
        </tr>

         <tr>
            <th class="p-2">ジャンル</th>
            <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></td>
         </tr>

         <tr>
            <th class="p-2">税込価格</th>
            <td><%= f.text_field :price, autofocus: true %>円</td>
         </tr>

         <tr>
            <th class="p-2">販売ステータス</th>
            <td>
              <%= f.radio_button :is_active, "true" %>
              <%= f.label :item_status, "販売中" %>
              <%= f.radio_button :is_active, "false" %>
              <%= f.label :item_status, "販売停止中" %>
            </td>
         </tr>

      </table>

      <div class="d-flex justify-content-center mr-3">
        <%= f.submit "変更を保存", class: "btn btn-success pr-3 pl-3" %>
      </div>

    <% end %>
    </div>
  </div>

</div>

app/views/admin/items/index.html.erb
<div class = "container">
  <div class="row">
    <div class="col-md-6">
      <div class = "m-5 text-black">
        <span class = "bg-light pr-3 pl-3 h5">商品一覧</span>
      </div>
    </div>


    <div class="col-md-6">
      <div class= "text-right m-5">
         <%= link_to new_admin_item_path, class: "btn btn-default" do %>
           <i class="fa-solid fa-plus"></i>
         <% end %>
      </div>
    </div>
  </div>


  <div class="row">

      <table width="100%">
        <thead class="bg-light">
          <tr>
            <th class="pt-2 pr-4 pl-4 pb-2">商品ID</th>
            <th class="pt-2 pr-4 pl-4 pb-2">商品名</th>
            <th class="pt-2 pr-4 pl-4 pb-2">税抜価格</th>
            <th class="pt-2 pr-4 pl-4 pb-2">ジャンル</th>
            <th class="pt-2 pr-4 pl-4 pb-2">ステータス</th>
          </tr>
        </thead>

        <tbody>
        <% @items.each do |item| %>

          <tr>
            <td class="p-3"><%= item.id %></td>
            <td class="p-3"><%= link_to item.name, admin_item_path(item.id) %></td>
            <td class="p-3"><%= item.price %></td>
            <td class="p-3"><%= item.genre.name %></td>
            <td class="p-3">
              <% if item.is_active %>
                <span class=text-success>販売中</span>
              <% else %>
                <span class=text-secondary>販売停止中</span>
              <% end %>
            </td>
          </tr>
        <% end %>

        </tbody>
      </table>

  </div>
  <%= paginate @items %>

</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class = "p-3 text-black">
      <span class = "bg-light pr-3 pl-3 h5">商品新規登録</span>
    </div>
  </div>

   <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
       <div class="d-flex justify-content-center m-3">
        <table>
          <tbody>

          <tr>
            <th class="pr-4 pb-2">
              商品画像
            </th>
            <td class="pr-4 pb-2">
              <%= f.file_field :image, accept: "image/*" %>
            </td>
          </tr>

          <tr>
            <th class="pr-4 pb-2">
              商品名
            </th>
            <td class="pr-4 pb-2">
              <%= f.text_field :name, autofocus: true, :placeholder => "商品名" %>
            </td>
          </tr>

          <tr>
            <th class="pr-4 pb-2">
              商品説明
            </th>
            <td class="pr-4 pb-2">
              <%= f.text_area :introduction, rows:3, autofocus: true, id:"inputIntroduction", :placeholder => "ここに説明文を記述します" %>
            </td>
          </tr>

          <tr>
            <th class="pr-4 pb-2">ジャンル</th>
            <td class="pr-4 pb-2">
              <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), {prompt: "選択して下さい", :class => "form-control-sm"} %>
            </td>
          </tr>

          <tr>
            <th class="pr-4 pb-2">税抜価格</th>
            <td class="pr-4 pb-2">
              <%= f.text_field :price, autofocus: true %>円
            </td>
          </tr>

          <tr>
            <th class="pr-4 pb-2">販売ステータス</th>
            <td class="pr-4 pb-2">
                <%= f.radio_button :is_active, "true" %>
                <%= f.label :item_status, "販売中" %>
                <%= f.radio_button :is_active, "false" %>
                <%= f.label :item_status, "販売停止中" %>
            </td>
          </tr>

        </tbody>
      </table>
    </div>

  <div class="d-flex justify-content-center m-3">
      <%= f.submit "新規登録", class: "btn btn-success" %>
  </div>
    <% end %>

   </div>
</div>

app/views/admin/items/show.html.erb
<div class = "container">
  <div class = "p-3 text-black">
    <span class = "bg-light pr-3 pl-3 h5">商品詳細</span>
  </div>

    <div class = "row m-3">
        <div class = "col-md-5">
          <% if @item.image.attached? %>
            <%= image_tag @item.image, size: "300x300" %>
          <% else %>
            <%= image_tag @item.get_profile_image(200, 200), size: "200x200" %>
          <% end %>
          </div>
        <div class = "col-md-7">
            <table>
              <thead>
                <tr>
                  <th class="p-2">商品名</th>
                  <td><%= @item.name %></td>
                </tr>

                <tr>
                  <th class="p-2">商品説明</th>
                  <td><%= @item.introduction %></td>
                </tr>

                <tr>
                  <th class="p-2">ジャンル</th>
                  <td><%= @item.genre.name %></td>
                </tr>

                <tr>
                  <th class="p-2">税込価格</br>
                  (税抜価格)</th>
                  <td><%= (@item.price*1.10).round.to_s + "（" + @item.price.to_s + "）" + "円" %></td>
                </tr>

                <tr>
                  <th class="p-2">販売ステータス</th>
                  <td>
                    <% if @item.is_active %>
                      <span class=text-success>販売中</span>
                    <% else %>
                      <span class=text-secondary>販売停止中</span>
                    <% end %>
                  </td>
                </tr>
              </thead>
            </table>
        </div>
    </div>

<div class="text-center">
  <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success btn-lg" %>
</div>

</div>