config/routes.rb
Rails.application.routes.draw do


 scope module: :public do

    root to: 'homes#top'
    get "/homes/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show ,:create] do
     collection { post 'confirm'}
     collection { get 'thanks'}
    end
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection { delete 'destroy_all'}
    end
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resource :customers, only: [:show, :edit, :update] do
     get 'confirm' => "customers#confirm"
     patch 'withdrawal' => "customers#withdrawal"
    end

 end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
    }

# 管理者用
# URL /admin/sign_in ...
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
 namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :customers, only: [:index, :show, :edit, :update] do
     resources :orders, only: [:index ,:show, :update]
     resources :order_details, only: [:update]
    end
    resources :genres, only: [:index, :show, :create, :edit, :update]

 end

 # scope module: :public do
 #    root 'homes#top'

 #    get 'customers/mypage' => 'customers#show', as: 'mypage'
 #    。
 #    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
 #    patch 'customers/information' => 'customers#update', as: 'update_information'
 #    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
 #    put 'customers/information' => 'customers#update'
 #    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
 #    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
 #    post 'orders/confirm' => 'orders#confirm'
 #    get 'orders/confirm' => 'orders#error'
 #    get 'orders/thanks' => 'orders#thanks', as: 'thanks'

 #    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
 #    resources :items, only: [:index, :show] do
 #      resources :cart_items, only: [:create, :update, :destroy]
 #    end
 #    resources :cart_items, only: [:index]
 #    resources :orders, only: [:new, :index, :create, :show]

 #  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :cart_items, dependent: :destroy
has_many :orders, dependent: :destroy
has_many :addresses, dependent: :destroy

 validates :is_deleted, inclusion: {in: [true, false]}

  def active_for_authenthication?
    super && !@customer.is_deleted
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to  admin_customer_path
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class = "p-3 text-black">
      <span class = "bg-light pr-3 pl-3 h5"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</span>
    </div>
  </div>

<!--bookersのユーザー情報編集画面を参考にする-->

 <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
  <div class="row">
    <div class="col-md-8">

      <table class="m-3">
        <thead>

            <tr>
              <th class="pr-4 pb-2">会員ID</th>
              <td class="pr-4 pb-2"><%= @customer.id %></td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">氏名</th>
              <td class="pr-4 pb-2">
                 <%= f.text_field :last_name %>
                 &emsp;
                 <%= f.text_field :first_name %>
              </td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">フリガナ</th>
              <td class="pr-4 pb-2">
                <%= f.text_field :last_name_kana %>
                &emsp;
                <%= f.text_field :first_name_kana %>
              </td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">郵便番号</th>
              <td class="pr-4 pb-2">
                <%= f.text_field :postal_code %>
              </td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">住所</th>
              <td class="pr-4 pb-2"><%= f.text_field :address, size: 40 %></td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">電話番号</th>
              <td class="pr-4 pb-2"><%= f.text_field :telephone_number %></td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">メールアドレス</th>
              <td class="pr-4 pb-2"><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">会員ステータス</th>
              <td class="pr-4 pb-2">
                <%= f.radio_button :is_deleted, "true" %>
                <%= f.label :customer_status, "退会" %>
                <%= f.radio_button :is_deleted, "false" %>
                <%= f.label :customer_status, "有効" %>
              </td>
              <!--会員ステータスの変更が反映されなかった；何故？-->
            </tr>

        </thead>
      </table>

    </div>
  </div>



    <div class="pl-5">
      <%= f.submit "変更を保存", class: "btn btn btn-success" %>
    </div>



 <% end %>

</div>

app/views/admin/customers/index.html.erb
<div class = "container">
  <div class = "p-3 text-black">
        <span class = "bg-light pr-3 pl-3 h5">会員一覧</span>
  </div>

  <div class = "col-md-8 mt-0 ml-5 mr-5 mb-5">
    <table>
      <thead class = "bg-light">
        <tr>
          <th class = "p-2">会員ID</th>
          <th class = "p-2">氏名</th>
          <th class = "p-2">メールアドレス</th>
          <th class = "p-2">ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @customers.each do |customer| %>

        <tr>
          <td class = "p-3"><%= customer.id %></td>
          <td class = "p-3"><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id)%></td>
          <td class = "p-3"><%= customer.email %></td>
          <td class = "p-3">
            <% if customer.is_deleted %>
              <span class=text-secondary>退会</span>
            <% else %>
              <span class=text-success>有効</span>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class = "p-3 text-black">
      <span class = "bg-light pr-3 pl-3 h5"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</span>
    </div>
  </div>
 <div class="row">
    <div class = "col-md-8">
      <table class="m-3">
        <tbody>

            <tr>
              <th class="pr-4 pb-2">会員ID</th>
              <td class="pr-4 pb-2"><%= @customer.id %></td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">氏名</th>
              <td class="pr-4 pb-2"><%= @customer.last_name + @customer.first_name %></td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">フリガナ</th>
              <td class="pr-4 pb-2"><%= @customer.last_name_kana + @customer.first_name_kana %></td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">郵便番号</th>
              <td class="pr-4 pb-2"><%= @customer.postal_code %></td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">住所</th>
              <td class="pr-4 pb-2"><%= @customer.address %></td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">電話番号</th>
              <td class="pr-4 pb-2"><%= @customer.telephone_number %></td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">メールアドレス</th>
              <td class="pr-4 pb-2"><%= @customer.email %></td>
            </tr>

            <tr>
              <th class="pr-4 pb-2">会員ステータス</th>
              <td class="pr-4 pb-2">
                <% if @customer.is_deleted %>
                  <span class=text-secondary>退会</span>
                <% else %>
                  <span class=text-success>有効</span>
                <% end %>
              </td>
            </tr>

        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 pl-5">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
      <%= link_to "注文履歴一覧を見る", admin_customer_order_path(@customer.id), class: "btn btn-primary" %>
    </div>
  </div>

</div>