config/routes.rb
Rails.application.routes.draw do


 scope module: :public do

    root to: 'homes#top'
    get "/homes/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show ,:create] do
     collection { post 'confirm'}
     collection { get 'thanks'}
    end
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection { delete 'destroy_all'}
    end
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resource :customers, only: [:show, :edit, :update] do
     get 'confirm' => "customers#confirm"
     patch 'withdrawal' => "customers#withdrawal"
    end

 end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
    }

# 管理者用
# URL /admin/sign_in ...
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
 namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :customers, only: [:index, :show, :edit, :update] do
     resources :orders, only: [:index ,:show, :update]
     resources :order_details, only: [:update]
    end
    resources :genres, only: [:index, :show, :create, :edit, :update]

 end

 # scope module: :public do
 #    root 'homes#top'

 #    get 'customers/mypage' => 'customers#show', as: 'mypage'
 #    。
 #    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
 #    patch 'customers/information' => 'customers#update', as: 'update_information'
 #    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
 #    put 'customers/information' => 'customers#update'
 #    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
 #    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
 #    post 'orders/confirm' => 'orders#confirm'
 #    get 'orders/confirm' => 'orders#error'
 #    get 'orders/thanks' => 'orders#thanks', as: 'thanks'

 #    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
 #    resources :items, only: [:index, :show] do
 #      resources :cart_items, only: [:create, :update, :destroy]
 #    end
 #    resources :cart_items, only: [:index]
 #    resources :orders, only: [:new, :index, :create, :show]

 #  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum method_of_payment: { credit_card: 0, transfer: 1}
  enum order_status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }

  def total_price
    total = 0
    order_details.each do |order_detail|
      total += order_detail.quantity * order_detail.purchase_price
      # [+=]をつかうことでeachをまわす毎に左側のtotalに右側の計算結果を足し上げられていく
    end
    return total
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    # @orders = Order.page(params[:page])
    @customer = Customer.find(params[:customer_id])
    @orders = @customer.orders.page(params[:page])
  end

  def show
    @order_details = Order.find(params[:id]).order_details
    #Orderモデルから特定のorderの情報を取りだし、それに紐づくorder_detailsのデータをとってくる
    @order = Order.find(params[:id])
    @order.total_amount =  @order.total_price
    # 各顧客の注文ごとの請求金額合計の算出用コード
  end

  def update
    @order_details = Order.find(params[:id]).order_details
    @order = Order.find(params[:id])

    if @order.update(order_params)

      @order_details.update_all(making_status: 1)
      redirect_to request.referer
    else
      redirect_to request.referer
      # @order_details.update_all(making_stastus: 1) if @order.order_status == "payment_confirmation"
      ## ①注文ステータスが「入金確認」とき、製作ステータスを全て「製作待ち」に更新する
      # 別の書き方
      # @order.status == "入金確認"
      # @order_details.each do |order_detail|
      #   order_detail.make_status = "製作待ち"
      #   order_detail.save
      # end
    end

    # admin_customer_order_path(@orders.customer.id)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <div class = "p-3 text-black">
        <span class = "bg-light pr-3 pl-3 h5"><%= @customer.last_name + @customer.first_name %>さんの注文履歴</span>
      </div>
    </div>
  </div>

  <div class="row">
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th>購入日時</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>

      <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to (l order.created_at), admin_customer_order_path(order.customer.id, order) %></td>
          <td><%= order.order_details.sum(:quantity) %></td>
          <td><%= order.order_status_i18n %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @orders %>

  </div>
</div>

app/views/admin/orders/show.html.erb
<div class = "container">
  <div class = "p-3 text-black">
      <span class = "bg-light pr-3 pl-3 h5">注文履歴詳細</span>
  </div>

    <table>
      <thead>
        <tr>
          <th class="p-2"><b>購入者</b></th>
          <td class="p-2"><%= link_to @order.customer.last_name + @order.customer.first_name, admin_customer_orders_path(@order.customer.id) %></td>
        </tr>

        <tr>
          <th class="p-2"><b>注文日</b></th>
          <td class="p-2"><%= l @order.created_at %></td>
        </tr>

        <tr>
          <th class="p-2"><b>配送先</b></th>
          <td class="p-2">
            〒<%= @order.post_code %>
            <%= @order.address %></br>
            <%= @order.mailling_label %>
          </td>
        </tr>

        <tr>
          <th class="p-2"><b>支払方法</b></th>
          <td class="p-2"><%= @order.method_of_payment_i18n %></td>
        </tr>

        <tr>
          <th class="p-2"><b>注文ステータス</b></th>
          <td class="p-2">
            <%= form_with model: @order, url: admin_customer_order_path(@order.id), method: :patch do |f| %>
              <%= f.select :order_status, Order.order_statuses_i18n.keys.map { |k| [I18n.t("enums.order.order_status.#{k}"), k] } %>
              <%= f.submit "更新", class: "btn btn-success" %>
            <% end %>
          </td>
        </tr>
      </thead>
    </table>

  <div class="row">
    <div class="col-md-8">
      <table class="table table-bordered m-2">
        <thead class="thead-light">
          <tr>
            <th class="p-2"><b>商品名</b></th>
            <th class="p-2"><b>単価(税込)</b></th>
            <th class="p-2"><b>数量</b></th>
            <th class="p-2"><b>小計</b></th>
            <th class="p-2"><b>製作ステータス</b></th>
          </tr>
        </thead>

        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td class="p-2"><%= order_detail.item.name %></td>
            <td class="p-2"><%= order_detail.item.with_tax_price %></td>
            <td class="p-2"><%= order_detail.quantity %></td>
            <td class="p-2"><%= (order_detail.item.price * 1.1).floor * order_detail.quantity %></td>
            <td class="p-2">
            <%= form_with model: order_detail, url: admin_customer_order_detail_path(@order.customer,order_detail), method: :patch do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map { |k| [I18n.t("enums.order_detail.making_status.#{k}"), k] } %>
              <%= f.submit "更新", class: "btn btn-success" %>
            <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4 pt-5">
      <table>
        <thead>
          <tr>
            <th class="p-2"><b>商品合計</b></th>
            <th class="p-2"><%= @order.total_amount.to_s(:delimited) %>円</th>
          </tr>

          <tr>
          <td class="p-2"><b>送料</b></td>
          <td class="p-2">800円</td>
          </tr>

          <tr>
            <td class="p-2"><b>請求金額合計</b></td>
            <td class="p-2"><b><%= (@order.total_amount + 800).to_s(:delimited)  %>円</b></td>
          </tr>
        </thead>
      </table>
    </div>
  </div>
</div>