config/routes.rb
Rails.application.routes.draw do


 scope module: :public do

    root to: 'homes#top'
    get "/homes/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show ,:create] do
     collection { post 'confirm'}
     collection { get 'thanks'}
    end
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection { delete 'destroy_all'}
    end
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resource :customers, only: [:show, :edit, :update] do
     get 'confirm' => "customers#confirm"
     patch 'withdrawal' => "customers#withdrawal"
    end

 end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
    }

# 管理者用
# URL /admin/sign_in ...
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
 namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :customers, only: [:index, :show, :edit, :update] do
     resources :orders, only: [:index ,:show, :update]
     resources :order_details, only: [:update]
    end
    resources :genres, only: [:index, :show, :create, :edit, :update]

 end

 # scope module: :public do
 #    root 'homes#top'

 #    get 'customers/mypage' => 'customers#show', as: 'mypage'
 #    。
 #    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
 #    patch 'customers/information' => 'customers#update', as: 'update_information'
 #    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
 #    put 'customers/information' => 'customers#update'
 #    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
 #    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
 #    post 'orders/confirm' => 'orders#confirm'
 #    get 'orders/confirm' => 'orders#error'
 #    get 'orders/thanks' => 'orders#thanks', as: 'thanks'

 #    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
 #    resources :items, only: [:index, :show] do
 #      resources :cart_items, only: [:create, :update, :destroy]
 #    end
 #    resources :cart_items, only: [:index]
 #    resources :orders, only: [:new, :index, :create, :show]

 #  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + address_name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true



end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

  # def self.cart_items_total_price
  #   total = []
  #   cart_items.each do |cart_item|
  #     total << cart_item.item.price * cart_item.amount
  #   end
  #   return (total.sum * 1.1).floor
  # end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :cart_items, dependent: :destroy
has_many :orders, dependent: :destroy
has_many :addresses, dependent: :destroy

 validates :is_deleted, inclusion: {in: [true, false]}

  def active_for_authenthication?
    super && !@customer.is_deleted
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

  validates :name, presence: true


end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  validates :is_active, inclusion: {in: [true, false]}

  has_one_attached :image

  def get_profile_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/flow01.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
   image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum method_of_payment: { credit_card: 0, transfer: 1}
  enum order_status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }

  def total_price
    total = 0
    order_details.each do |order_detail|
      total += order_detail.quantity * order_detail.purchase_price
      # [+=]をつかうことでeachをまわす毎に左側のtotalに右側の計算結果を足し上げられていく
    end
    return total
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])#ページネーションを使用
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @items = Item.page(params[:page])
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  # def after_sign_in_path_for(resource_or_scope)
  #   if resource_or_scope == :admin
  #     admin_root_path
  #   else resource_or_scope == :public
  #     customer_path(@customer.id)
  #   end
  #   #ログイン主がadminの時、ログイン後の遷移先はadminのトップ画面になる
  #   #ログイン主がcustomerの時、ログイン後の遷移先はcustomerのshow画面になる
  # end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
    #ログイン主がadminの時、ログアウト後の遷移先はログイン画面になる
    #ログイン主がcustomerの時、ログアウト後の遷移先はpublicのトップ画面になる
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--  <head>-->
<!--    <title>NaganoCake</title>-->
<!--    <meta name="viewport" content="width=device-width,initial-scale=1">-->
<!--    %= csrf_meta_tags %>-->
<!--    %= csp_meta_tag %>-->

<!--<script src="https://kit.fontawesome.com/6f9ca60165.js" crossorigin="anonymous"></script>-->
<!--    %= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>-->
<!--    %= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>-->
<!--  </head>-->

<!--  <body>-->
<!--    <header class="shadow-sm">-->
<!--    <nav class="navbar navbar-expand-lg navbar-light">-->
<!--      <div class="container">-->
<!--        %= link_to 'LOGO', root_path, class: ' navbar-brand' %>-->
<!--          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
<!--            <span class="navbar-toggler-icon"></span>-->
<!--          </button>-->

<!--          % if current_customer %>-->
<!--            ようこそ！%= current_customer.last_name %>さん-->
<!--          % end %>-->
          <!--ログインしている顧客の名前付きフラッシュメッセージを表示-->

<!--        <div class="collapse navbar-collapse" id="navbarNavDropdown">-->
<!--          <ul class="navbar-nav ml-auto">-->
<!--          % if admin_signed_in? %>-->
<!--            <li class="nav-item">-->
<!--              %= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--            <li class="nav-item">-->
<!--              %= link_to "会員一覧",  admin_customers_path, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--            <li class="nav-item">-->
<!--              %= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--            <li class="nav-item">-->
<!--              %= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--            <li class="nav-item">-->
<!--              %= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->
<!--            % end %>-->

<!--          % elsif customer_signed_in? %>-->
<!--            <li class="nav-item">-->
<!--              %= link_to "マイページ", customers_path, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--            <li class="nav-item">-->
<!--              %= link_to "商品一覧", items_path, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--            <li class="nav-item">-->
<!--              %= link_to "カート", cart_items_path, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--            <li class="nav-item">-->
<!--              %= link_to "ログアウト",  destroy_customer_session_path, method: :delete, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--          % else %>-->
<!--            <li class="nav-item">-->
<!--              %= link_to "About", about_path, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--            <li class="nav-item">-->
<!--              %= link_to "商品一覧", items_path, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--            <li class="nav-item">-->
<!--              %= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--            <li class="nav-item">-->
<!--              %= link_to "ログイン", customer_session_path, class: 'nav-link text-dark border border-dark rounded m-2' %>-->
<!--            </li>-->

<!--          % end %>-->
<!--          </ul>-->
<!--        </div>-->
<!--      </div>-->
<!--    </nav>-->

<!--    <div class="text-right pb-3">-->
<!--      %= form_with local:true, method: :get do |form| %>-->
<!--        %= form.text_field :keybord, :placeholder => "Search" %>-->
<!--        %= form.submit '検索' %>-->
<!--      % end %>-->
<!--    </div>-->
    <!--検索機能の実装フォーム-->

<!--    </header>-->
<!--    %= yield %>-->
<!--  </body>-->
<!--</html>-->

<!DOCTYPE html>
<html>
  <head>
    <title>Onni</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <script src="https://kit.fontawesome.com/6f9ca60165.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">

          <%= link_to 'Onni', root_path, class: ' navbar-brand' %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                     aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <% if current_customer %>
            ようこそ！<%= current_customer.last_name %>さん
          <% end %>
          <!--ログインしている顧客の名前付きフラッシュメッセージを表示-->

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "会員一覧",  admin_customers_path, class: 'nav-link text-dark border border-dark rounded m-2' %>
              </li>

              <li class="nav-item">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark border border-dark rounded m-2' %>
              </li>

              <li class="nav-item">
                <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-dark border border-dark rounded m-2' %>
              </li>

              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark
                    border border-dark rounded m-2' %>
              </li>

            <% elsif customer_signed_in? %>
              <li class="nav-item">
                <%= link_to customers_path, class: 'nav-link text-dark border border-dark rounded m-2' do %>
                  マイページ
                  <i class="fas fa-user"></i>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to items_path, class: 'nav-link text-dark border border-dark rounded m-2' do %>
                  商品一覧
                  <i class="fas fa-weight-hanging"></i>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to cart_items_path, class: 'nav-link text-dark border border-dark rounded m-2' do %>
                  カート
                  <i class="fas fa-shopping-cart"></i>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-dark
                    border border-dark rounded m-2' do %>
                  ログアウト
                  <i class="fas fa-sign-out-alt"></i>
                <% end %>
              </li>


            <% else %>
              <li class="nav-item">
                <%= link_to about_path, class: 'nav-link text-dark border border-dark rounded m-2' do %>
                  Onniについて
                  <i class="fas fa-store-alt"></i>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to items_path, class: 'nav-link text-dark border border-dark rounded m-2' do %>
                  商品一覧
                  <i class="fas fa-weight-hanging"></i>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_customer_registration_path, class: 'nav-link text-dark border border-dark rounded m-2' do %>
                  新規登録
                  <i class="fas fa-user-plus"></i>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to customer_session_path, class: 'nav-link text-dark border border-dark rounded m-2' do %>
                  ログイン
                  <i class="fas fa-sign-in-alt"></i>
                <% end %>
              </li>

            <% end %>

            </ul>

          </div>
        </div>
      </nav>

    </header>

    <%= yield %>

    <!--% if Rails.env.development? %>-->
    <!--  %= debug params %><br>-->
    <!--  %= "admin:#{current_admin.inspect}" %><br>-->
    <!--  %= "customer:#{current_customer.inspect}" %>-->
    <!--% end %>-->
    <!--デバックツールとして有用-->

  </body>
</html>